skills = {
    "Software Engineer": [
        "Data Structures and Algorithms",
        "System Design",
        "Microservices Architecture",
        "Cloud Computing (AWS, Azure, GCP)",
        "Containerization (Docker, Kubernetes)",
        "Backend Frameworks (Spring Boot, Django, Node.js)",
        "Frontend Frameworks (React, Angular, Vue.js)",
        "CI/CD Pipelines",
        "Database Optimization (SQL & NoSQL)",
        "API Development (REST, GraphQL)",
    ],
    "Quality Assurance": [
        "Automated Testing (Selenium, Cypress, Playwright)",
        "Performance Testing (JMeter, LoadRunner)",
        "Security Testing (OWASP, Burp Suite)",
        "API Testing (Postman, REST Assured)",
        "CI/CD Integration for Testing",
        "Test-Driven Development (TDD)",
        "Behavior-Driven Development (BDD - Cucumber)",
        "Version Control (Git, GitHub, GitLab)",
        "Containerization Testing (Docker, Kubernetes)",
        "Scripting for Automation (Python, Bash)",
    ],
    "Business Analyst": [
        "Requirement Gathering & Analysis",
        "Data Visualization (Tableau, Power BI)",
        "SQL for Data Analysis",
        "Process Modeling (BPMN, UML)",
        "Agile & Scrum Methodologies",
        "Stakeholder Communication",
        "Prototyping Tools (Figma, Balsamiq)",
        "Statistical Analysis",
        "Cloud Computing Basics",
        "Enterprise Resource Planning (ERP)",
    ],
    "Cyber Security": [
        "Penetration Testing (Metasploit, Burp Suite)",
        "Network Security (Firewalls, VPNs, IDS/IPS)",
        "Cloud Security (AWS Security, Azure Security)",
        "Encryption & Cryptography",
        "Security Information and Event Management (SIEM)",
        "Ethical Hacking",
        "Threat Intelligence",
        "Secure Coding Practices",
        "Incident Response & Forensics",
        "Zero Trust Architecture",
    ],
    "Network Engineer": [
        "Routing & Switching (Cisco, Juniper)",
        "Network Security (Firewall, VPN, IDS/IPS)",
        "Cloud Networking (AWS VPC, Azure Virtual Network)",
        "Wireless Networking",
        "Load Balancing & Traffic Engineering",
        "Automation & Scripting (Python, Ansible)",
        "Network Monitoring (Nagios, Wireshark)",
        "SDN & NFV (Software-Defined Networking)",
        "IPv6 & Subnetting",
        "BGP & OSPF Configuration",
    ],
    "Mobile App Developer": [
        "Cross-Platform Development (Flutter, React Native)",
        "Native App Development (Swift, Kotlin)",
        "Mobile UI/UX Design Principles",
        "Performance Optimization",
        "REST & GraphQL APIs",
        "Mobile Security Best Practices",
        "Push Notifications & Background Services",
        "State Management (Redux, Provider, Riverpod)",
        "Testing Frameworks (JUnit, Espresso, XCTest)",
        "App Store Deployment & Optimization",
    ],
    "Devops": [
        "Infrastructure as Code (Terraform, Ansible, CloudFormation)",
        "CI/CD Pipelines (Jenkins, GitHub Actions, GitLab CI)",
        "Containerization & Orchestration (Docker, Kubernetes)",
        "Monitoring & Logging (Prometheus, Grafana, ELK Stack)",
        "Cloud Platforms (AWS, Azure, GCP)",
        "Security in DevOps (DevSecOps)",
        "Version Control & GitOps",
        "Networking & Load Balancing",
        "Scripting & Automation (Bash, Python)",
        "Serverless Computing",
    ],
    "Machine Learning Engineer": [
        "Supervised & Unsupervised Learning",
        "Deep Learning (TensorFlow, PyTorch)",
        "Natural Language Processing (NLP)",
        "Computer Vision (OpenCV, YOLO)",
        "Big Data Processing (Spark, Dask)",
        "Model Optimization & Hyperparameter Tuning",
        "Deploying ML Models (Flask, FastAPI, AWS SageMaker)",
        "Reinforcement Learning",
        "Feature Engineering",
        "Explainable AI (XAI)",
    ],
    "Data Engineer": [
        "ETL Pipelines (Apache Airflow, Luigi)",
        "Big Data Technologies (Hadoop, Spark)",
        "Data Warehousing (Redshift, BigQuery, Snowflake)",
        "Streaming Data Processing (Kafka, Flink)",
        "Database Design & Optimization",
        "Cloud Data Engineering (AWS Glue, Azure Data Factory)",
        "Data Governance & Security",
        "Python & SQL for Data Processing",
        "Infrastructure as Code (Terraform, Ansible)",
        "Data Modeling & Schema Design",
    ],
    "Data Science": [
        "Exploratory Data Analysis (EDA)",
        "Statistical Modeling & Hypothesis Testing",
        "Predictive Analytics",
        "Machine Learning Algorithms",
        "Data Wrangling & Cleaning",
        "Data Visualization (Matplotlib, Seaborn, Plotly)",
        "Cloud-based AI Solutions",
        "Deploying Models (Flask, FastAPI, Docker)",
        "Big Data Analytics (Spark, Hadoop)",
        "Time Series Analysis",
    ],
}

courses = {
    "Software Engineer": [
        {"name": "Amazon Junior Software Developer Professional Certificate", "url": "https://www.coursera.org/professional-certificates/amazon-junior-software-developer"},
        {"name": "IBM Full Stack Software Developer Professional Certificate", "url": "https://www.coursera.org/professional-certificates/ibm-full-stack-cloud-developer"},
        {"name": "Microservices with Spring Boot and Spring Cloud", "url": "https://www.udemy.com/course/microservices-with-spring-boot-and-spring-cloud/"},
        {"name": "Become a Successful Software Programming Developer/ Engineer", "url": "https://www.udemy.com/course/how-to-become-a-successful-software-programming-developer/"},
        {"name": "Microsoft Full-Stack Developer Professional Certificate", "url": "https://www.coursera.org/professional-certificates/microsoft-full-stack-developer"},
    ],
    "Quality Assurance": [
        {"name": "Automated Software Testing", "url": "https://www.coursera.org/specializations/software-testing-automation"},
        {"name": "Foundations of Software Testing and Validation", "url": "https://www.coursera.org/learn/foundations-of-software-testing-and-validation"},
        {"name": "Software Testing for Developers", "url": "https://www.coursera.org/learn/codio-software-testing-for-developers"},
        {"name": "The Complete 2025 Software Testing Bootcamp", "url": "https://www.udemy.com/course/testerbootcamp/"},
        {"name": "MasterClass Software Testing with Jira & Agile -Be a QA Lead", "url": "https://www.udemy.com/course/learn-software-testing-in-practical-become-a-qa-expert/"},
    ],
    "Business Analyst": [
        {"name": "IBM Business Analyst Professional Certificate", "url": "https://www.coursera.org/professional-certificates/ibm-business-analyst-professional-certificate"},
        {"name": "Business Analysis & Process Management", "url": "https://www.coursera.org/projects/business-analysis-process-management"},
        {"name": "Microsoft Business Analyst Professional Certificate", "url": "https://www.coursera.org/professional-certificates/microsoft-business-analyst"},
        {"name": "The Business Intelligence Analyst Course 2025", "url": "https://www.udemy.com/course/the-business-intelligence-analyst-course-2018/"},
        {"name": "Business Analyst Bootcamp: Excel, Stats, SQL, Tableau", "url": "https://www.udemy.com/course/technical-business-analytics-for-agile-decision-making/"},
    ],
    "Cyber Security": [
        {"name": "Cyber Security Fundamentals", "url": "https://www.coursera.org/specializations/intro-cyber-security"},
        {"name": "IBM Cybersecurity Analyst Professional Certificate", "url": "https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst"},
        {"name": "Microsoft Cybersecurity Analyst Professional Certificate", "url": "https://www.coursera.org/professional-certificates/microsoft-cybersecurity-analyst"},
        {"name": "Cyber Security: From Beginner to Expert", "url": "https://www.udemy.com/course/cybersecurity-from-beginner-to-expert/"},
        {"name": "The Complete Certified in Cybersecurity CC course ISC2 2025", "url": "https://www.udemy.com/course/certifiedincybersecurity/"},
    ],
    "Network Engineer": [
        {"name": "Introduction to Networking", "url": "https://www.coursera.org/learn/introduction-to-networking-nvidia"},
        {"name": "Akamai Network Engineering Professional Certificate", "url": "https://www.coursera.org/professional-certificates/akamai-network-engineering"},
        {"name": "Google IT Support Professional Certificate", "url": "https://www.coursera.org/professional-certificates/google-it-support"},
        {"name": "The Complete Networking Fundamentals Course. Your CCNA start", "url": "https://www.udemy.com/course/complete-networking-fundamentals-course-ccna-start/"},
        {"name": "Network Engineer (IT Boot Camp) From Zero To Hero. (WAN)", "url": "https://www.udemy.com/course/network-engineer-it-boot-camp-from-zero-to-hero/"},
    ],
    "Mobile App Developer": [
        {"name": "Introduction to Mobile App Development", "url": "https://www.coursera.org/learn/introduction-to-mobile-app-development"},
        {"name": "Meta Android Developer Professional Certificate", "url": "https://www.coursera.org/professional-certificates/meta-android-developer"},
        {"name": "Meta iOS Developer Professional Certificate", "url": "https://www.coursera.org/professional-certificates/meta-ios-developer"},
        {"name": "iOS & Swift - The Complete iOS App Development Bootcamp", "url": "https://www.udemy.com/course/ios-13-app-development-bootcamp/"},
        {"name": "The Complete Flutter Development Bootcamp with Dart", "url": "https://www.udemy.com/course/flutter-bootcamp-with-dart/"},
    ],
    "DevOps": [
        {"name": "IBM DevOps and Software Engineering Professional Certificate", "url": "https://www.coursera.org/professional-certificates/devops-and-software-engineering"},
        {"name": "DevOps on AWS Specialization", "url": "https://www.coursera.org/specializations/aws-devops"},
        {"name": "Getting Started with Azure DevOps Boards", "url": "https://www.coursera.org/projects/getting-started-azure-devops-boards"},
        {"name": "DevOps Beginners to Advanced with Projects", "url": "https://www.udemy.com/course/decodingdevops/"},
        {"name": "AWS Certified DevOps Engineer Professional 2025 - DOP-C02", "url": "https://www.udemy.com/course/aws-certified-devops-engineer-professional-hands-on/"},
    ],
    "Machine Learning Engineer": [
        {"name": "Machine Learning by Andrew Ng", "url": "https://www.coursera.org/learn/machine-learning"},
        {"name": "Deep Learning Specialization", "url": "https://www.coursera.org/specializations/deep-learning"},
        {"name": "Microsoft AI & ML Engineering Professional Certificate", "url": "https://www.coursera.org/professional-certificates/microsoft-ai-and-ml-engineering"},
        {"name": "Python for Computer Vision with OpenCV and Deep Learning", "url": "https://www.udemy.com/course/python-for-computer-vision-with-opencv-and-deep-learning/"},
        {"name": "Complete MLOps Bootcamp With 10+ End To End ML Projects", "url": "https://www.udemy.com/course/complete-mlops-bootcamp-with-10-end-to-end-ml-projects/"},
    ],
    "Data Engineer": [
        {"name": "IBM Data Engineering Professional Certificate", "url": "https://www.coursera.org/professional-certificates/ibm-data-engineer"},
        {"name": "NoSQL, Big Data, and Spark Foundations Specialization", "url": "https://www.coursera.org/specializations/nosql-big-data-and-spark-foundations"},
        {"name": "Big Data Specialization", "url": "https://www.coursera.org/specializations/big-data"},
        {"name": "AWS Certified Data Engineer Associate 2025 - Hands On!", "url": "https://www.udemy.com/course/aws-data-engineer/"},
        {"name": "Data Engineering for Beginners: Learn SQL, Python & Spark", "url": "https://www.udemy.com/course/data-engineering-essentials-sql-python-and-spark/"},
        
    ],
    "Data Science": [
        {"name": "IBM Data Science Professional Certificate", "url": "https://www.coursera.org/professional-certificates/ibm-data-science"},
        {"name": "Python for Data Science, AI & Development", "url": "https://www.coursera.org/learn/python-for-applied-data-science-ai"},
        {"name": "Data Science Specialization", "url": "https://www.coursera.org/specializations/jhu-data-science"},
        {"name": "The Data Science Course: Complete Data Science Bootcamp 2025", "url": "https://www.udemy.com/course/the-data-science-course-complete-data-science-bootcamp/"},
        {"name": "Complete Data Science,Machine Learning,DL,NLP Bootcamp", "url": "https://www.udemy.com/course/complete-machine-learning-nlp-bootcamp-mlops-deployment/"},
    ],
}


resume_videos = [ 'https://youtu.be/Tt08KmFfIYQ','https://youtu.be/y8YH0Qbu5h4',
                  'https://youtu.be/u75hUSShvnc','https://youtu.be/BYUy1yvjHxE',
                  'https://youtu.be/KFaugkGVeNQ','https://youtu.be/3agP4x8LYFM',
                  'https://youtu.be/GyjzOKdaioU','https://youtu.be/17YZBH_qtmg',
                  'https://youtu.be/C7pNLIq3kOI','https://youtu.be/xpaz7nrNmXA',
                  'https://youtu.be/aKjsy-b00QM']

interview_videos = ['https://youtu.be/HG68Ymazo18','https://youtu.be/BOvAAoxM4vg',
                    'https://youtu.be/KukmClH1KoA','https://youtu.be/7_aAicmPB3A',
                    'https://youtu.be/1mHjMNZZvFo','https://youtu.be/WfdtKbAJOmE',
                    'https://youtu.be/IBjM-F56qS0','https://youtu.be/IBjM-F56qS0',
                    'https://youtu.be/4tYoVx0QoN0','https://youtu.be/Ge0Udbws1kc',
                    'https://youtu.be/thkuu_FWFD8','https://youtu.be/e0E6-dRPcJA',
                    'https://youtu.be/htT1bhFSNxo','https://youtu.be/TZ3C_syg9Ow']
